### ISSUE TITLE
I’m having a problem with whole baserom.us.z64 thing.

### ISSUE THREAD

**Issue by TheMamaMiaGuy** [Hydr8gon/sm64#13]
So I have a majority of the things used for the compile prepared. I have a US rom version of the super Mario 64. I have docker installed and I have the sm64-nds file installed as well. I extracted it and I put the US version of super Mario 64 into the sm64-nds file and renamed it “baserom.us.z64”. I ran the build-docker.bat file and it gave me an error. The error said:  “error during connect: This error may indicate that the docker daemon is not running.: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=sm64dsi&target=&ulimits=null&version=1": open //./pipe/docker_engine: The system cannot find the file specified.
docker: error during connect: This error may indicate that the docker daemon is not running.: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/create": open //./pipe/docker_engine: The system cannot find the file specified.
See 'docker run --help'.
Press any key to continue . . .” In the CMD. Whenever I try it using administrator, it tells me: “A Super Mario 64 ROM is required to extract the assets and build the game.
Please place one in the same directory as this script, it should be named:
 - baserom.us.z64 for the USA version - recommended
 - baserom.eu.z64 for the European version
 - baserom.jp.z64 for the Japanese version
 - baserom.sh.z64 for the Japanese rumble pak edition
Press any key to continue . . .”. Could someone please help me through this issue! Please!

**Comment by Hydr8gon** [comment]
Honestly I'm not really sure, I don't use Windows and I haven't gone through the Docker instructions myself. One thing I can think of is that running as administrator could be changing the working directory, which makes it unable to find the file? If you're comfortable enough in command prompt, it might be worth opening an administator session, manually `cd`ing to the folder, and running the batch file from there.

**Comment by TheMamaMiaGuy** [comment]
> Honestly I'm not really sure, I don't use Windows and I haven't gone through the Docker instructions myself. One thing I can think of is that running as administrator could be changing the working directory, which makes it unable to find the file? If you're comfortable enough in command prompt, it might be worth opening an administator session, manually `cd`ing to the folder, and running the batch file from there.

Quick question, did you use Ubuntu. If so, then I’ll just have to use that…

**Comment by Hydr8gon** [comment]
I'm on Arch, but the Linux instructions in the readme cover most popular distros so Ubuntu or anything else is fine. Sorry it's giving you so much trouble, I wish I could help more :/

**Comment by TheMamaMiaGuy** [comment]
> I'm on Arch, but the Linux instructions in the readme cover most popular distros so Ubuntu or anything else is fine. Sorry it's giving you so much trouble, I wish I could help more :/

Don’t worry man, it’s cool. I’m sure we can get something figured out.

**Comment by TheMamaMiaGuy** [comment]
If I have to, I might use Arch just so things are easier.

**Comment by Alexboy2334** [comment]
> If I have to, I might use Arch just so things are easier.

If you have problems compiling I can provide you with the patch file that can be applied with Floating IPS.

Hydr8gon I certainly don't want to do illegal actions, but I believe the patch is legal and is a method used for New Super Mario Bros co-op as well. I know the patch content might refer to the original rom, but I just want to help this guy cause I also had an issue like this.

**Comment by TheMamaMiaGuy** [comment]
> > If I have to, I might use Arch just so things are easier.
> 
> If you have problems compiling I can provide you with the patch file that can be applied with Floating IPS.
> 
> Hydr8gon I certainly don't want to do illegal actions, but I believe the patch is legal and is a method used for New Super Mario Bros co-op as well. I know the patch content might refer to the original rom, but I just want to help this guy cause I also had an issue like this.

What’s the patch for?

**Comment by TheMamaMiaGuy** [comment]
Update! I went ahead and installed Ubuntu and followed the instructions and I actually got further! However, at the end of the compiling process it told me: 

==== Build Options ====
Version:        us
Microcode:      f3dex2
Target:         sm64.us
Compare ROM:    no
Build Matching: no
=======================
Building tools...
Building ROM...
Preprocessing level make rules: build/us_nds/level_rules.mk 
make: /opt/devkitpro/devkitARM/bin/arm-none-eabi-cpp: Command not found
make: *** [Makefile.split:165: build/us_nds/level_rules.mk] Error 127
antman5000@antman5000-Satellite-L55-A:~/sm64$ 

I have an idea on how to solve this and I think it has something to do with DevKitPro. I didn’t install it so that may be the problem.

**Comment by Antman5000** [comment]
I just figured

**Comment by TheMamaMiaGuy** [comment]
> > I'm on Arch, but the Linux instructions in the readme cover most popular distros so Ubuntu or anything else is fine. Sorry it's giving you so much trouble, I wish I could help more :/
> 
 I just figured out that devkitpro Pac-Man can’t be installed on Ubuntu, or at least I think it can’t.
I’ll really just have to install arch…

**Comment by TheMamaMiaGuy** [comment]
At this point, I’m wondering if one of one guys can email to me through gmail. Would that be possible?

**Comment by Hydr8gon** [comment]
Heh, setting up an Arch installation isn't really a straightforward thing to do if you haven't done it before. devkitPro pacman should work fine on Ubuntu, just install the package from [here](https://github.com/devkitPro/pacman/releases/tag/v1.0.2) and use it as `dkp-pacman` in the terminal.

**Comment by TheMamaMiaGuy** [comment]
> Heh, setting up an Arch installation isn't really a straightforward thing to do if you haven't done it before. devkitPro pacman should work fine on Ubuntu, just install the package from [here](https://github.com/devkitPro/pacman/releases/tag/v1.0.2) and use it as `dkp-pacman` in the terminal.

Well, I found this respiratory earlier today and I tried it out for myself but it didn’t work. I’m assuming it was my fault because I really had no clue of what I was doing in the first place. Could you run me through a step by step process on how to install it on Ubuntu because I’m an idiot? Oh, and what about the gmail option? After all, it wouldn’t be pubic...

**Comment by Alexboy2334** [comment]
> > Heh, setting up an Arch installation isn't really a straightforward thing to do if you haven't done it before. devkitPro pacman should work fine on Ubuntu, just install the package from [here](https://github.com/devkitPro/pacman/releases/tag/v1.0.2) and use it as `dkp-pacman` in the terminal.
> 
> Well, I found this respiratory earlier today and I tried it out for myself but it didn’t work. I’m assuming it was my fault because I really had no clue of what I was doing in the first place. Could you run me through a step by step process on how to install it on Ubuntu because I’m an idiot? Oh, and what about the gmail option? After all, it wouldn’t be pubic...

If you have a Github account we can meet there.

**Comment by TheMamaMiaGuy** [comment]
> If you have a Github account we can meet there.

I have a GitHub account, so that’ll be fine.

**Comment by Alexboy2334** [comment]
> > If you have a Github account we can meet there.
> 
> I have a GitHub account, so that’ll be fine.

I'm sorry I meant a Gbatemp account, also because it is much easier to communicate there. Sorry for the confusion I write in a hurry sometimes 😅. You can just tell me the account name if you have it.

**Comment by Hydr8gon** [comment]
Hey, sorry I went missing yesterday; I was working on something else and got totally distracted. I can try to give some quick instructions, but this is just based on the dkp-pacman release page and my memory.
1. Download `devkitpro-pacman.amd64.deb` from the [devkitPro pacman release page](https://github.com/devkitPro/pacman/releases) (assuming you're on a standard desktop/laptop, if you have an ARM device you'll want the other one)
2. Run `sudo apt install gdebi-core` to install a tool that lets you manually install packages on Ubuntu, then navigate to the directory where the downloaded package is and run `sudo gdebi devkitpro-pacman.amd64.deb`
3. Maybe reboot? Then run `sudo dkp-pacman -S nds-dev` to install the NDS development tools (if there are issues, run `sudo dkp-pacman -Syu` to update the database)
4. Maybe reboot again? From here you should have all the devkitPro stuff set up, so refer to the [Linux instructions](https://github.com/Hydr8gon/sm64#linux-installation) to install additional dependencies and compile.

**Comment by TheMamaMiaGuy** [comment]
> Hey, sorry I went missing yesterday; I was working on something else and got totally distracted. I can try to give some quick instructions, but this is just based on the dkp-pacman release page and my memory.
> 
> 1. Download `devkitpro-pacman.amd64.deb` from the [devkitPro pacman release page](https://github.com/devkitPro/pacman/releases) (assuming you're on a standard desktop/laptop, if you have an ARM device you'll want the other one)
> 2. Run `sudo apt install gdebi-core` to install a tool that lets you manually install packages on Ubuntu, then navigate to the directory where the downloaded package is and run `sudo gdebi devkitpro-pacman.amd64.deb`
> 3. Maybe reboot? Then run `sudo dkp-pacman -S nds-dev` to install the NDS development tools (if there are issues, run `sudo dkp-pacman -Syu` to update the database)
> 4. Maybe reboot again? From here you should have all the devkitPro stuff set up, so refer to the [Linux instructions](https://github.com/Hydr8gon/sm64#linux-installation) to install additional dependencies and compile.

Alright, thanks for the instructions. I’ll try it out soon.

**Comment by TheMamaMiaGuy** [comment]
Thank you my guy! it worked! i was able to compile it!

**Comment by TheMamaMiaGuy** [comment]
Now how do I launch it since it doesn’t work on TLWiLightmenu++? By the way, I’m using 3ds.

**Comment by Hydr8gon** [comment]
Awesome, I'm glad it finally worked out! For launching it, seems like you're in luck; TWiLightMenu compatibilty was [just fixed](https://github.com/Hydr8gon/sm64/issues/5#issuecomment-834131123)! You'll just have to wait for a new release, or grab the latest nightly build from [GitHub Actions](https://github.com/DS-Homebrew/TWiLightMenu/actions).

**Comment by TheMamaMiaGuy** [comment]
> Awesome, I'm glad it finally worked out! For launching it, seems like you're in luck; TWiLightMenu compatibilty was [just fixed](https://github.com/Hydr8gon/sm64/issues/5#issuecomment-834131123)! You'll just have to wait for a new release, or grab the latest nightly build from [GitHub Actions](https://github.com/DS-Homebrew/TWiLightMenu/actions).

Alright, thanks for letting me know!
