### ISSUE TITLE
wont build 

### ISSUE THREAD

**Issue by LhymeFruit** [Hydr8gon/sm64#17]
I was following the instructions fully but when I opened the build batch file it says

"error during connect: This error may indicate that the docker daemon is not running.: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=sm64dsi&target=&ulimits=null&version=1": open //./pipe/docker_engine: The system cannot find the file specified.
docker: error during connect: This error may indicate that the docker daemon is not running.: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/create": open //./pipe/docker_engine: The system cannot find the file specified.
See 'docker run --help'.
Press any key to continue . . ."

any fixes?

**Comment by CrezyDud** [comment]
its a docker problem,
mr minecraft, read the log and go to thier website (litterally posted it)
and use thier fix to start to docker daemon

**Comment by LhymeFruit** [comment]
> its a docker problem, mr minecraft, read the log and go to thier website (litterally posted it) and use thier fix to start to docker daemon

it took you months for that

**Comment by LhymeFruit** [comment]
> its a docker problem, mr minecraft, read the log and go to thier website (litterally posted it) and use thier fix to start to docker daemon

doesnt matter i found someone willing to give me the pre built rom
