### ISSUE TITLE
I do not understand how to do any of this

### ISSUE THREAD

**Issue by Backontrack64** [Hydr8gon/sm64#29]
Please help I don't understand how to do this I downloaded the rom and the sm64 nds but I don't know how to get the game since I don't know if you use docker to get the game can someone explain step by step please

**Comment by Hydr8gon** [comment]
On Windows:
* Install Docker Desktop from [here](https://www.docker.com/get-started)
* Download SM64DSi from [here](https://github.com/Hydr8gon/sm64/archive/nds.zip)
* Copy the `sm64-nds` folder from the zip file to your computer
* Rename an SM64 ROM to `baserom.us.z64` and place it in the folder
* Find the `build_docker.bat` file in the folder and run it
* Navigate to the `sm64-nds/build/us_nds` folder to find a new ROM called `sm64.us.nds`

**Comment by Backontrack64** [comment]
Thank you so much
