### ISSUE TITLE
`error: implicit declaration of function 'enableSound'` when building using Docker

### ISSUE THREAD

**Issue by bemxio** [Hydr8gon/sm64#42]
Hello, I am trying to build the DSi port with Docker, however after extracting assets and building binaries, it returns:
```
src/nds/arm7/main.c: In function 'main':
src/nds/arm7/main.c:43:5: error: implicit declaration of function 'enableSound' [-Wimplicit-function-declaration]
   43 |     enableSound();
      |     ^~~~~~~~~~~
make: *** [Makefile:779: build/us_nds/arm7/src/nds/arm7/main.o] Error 1
```

Maybe devkitARM has had some major change that broke that, or perhaps it could be an issue on my side?

**Comment by Hydr8gon** [comment]
That's my bad for not merging #41 sooner. It should work with the latest source now.

**Comment by bemxio** [comment]
Hmm, seems like that's not it, I tried re-building the ROM, removing my previous downloaded images and container but it still returns that error at the same moment as before.

**Comment by Hydr8gon** [comment]
Oh yeah, the flag needs to be set for the ARM7 as well. It should be fixed for real this time!

**Comment by bemxio** [comment]
Yup, the ROM builds nicely without any errors now, thank you!
